services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: prj_blog
      POSTGRES_PASSWORD: gMEduA322af3QiyqEwIUkL4h7S4YegO
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
